# Generated by Django 3.2.4 on 2021-06-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webqrcode',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
