# Generated by Django 3.2.4 on 2021-06-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_webqrcode_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='webqrcode',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
