# Generated by Django 3.2.4 on 2021-06-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_webqrcode_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webqrcode',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
